
<div class="row">
    <div class="col-md-12">

        <div class="form-group">
            <label>資料夾總數量</label>
            <input type="text" class="form-control" value="<?php echo escape($information['num_folders']); ?>" readonly />
        </div>

        <div class="row">
            <div class="col-md-7">

                <label>資料夾索引列表 x <?php echo count($information['devlogs']); ?></label>
                <ol>
                    <?php
                        foreach ( $information['devlogs'] as $path ) {
                            echo "<li>";
                            echo basename(dirname($path));
                            echo "</li>";
                        }
                    ?>
                </ol>

            </div>
            <div class="col-md-5">

                <div class="form-group">
                    <label>索引 tag 數量</label>
                    <input type="text" class="form-control" value="<?php echo escape($information['num_tags']); ?>" readonly />
                </div>
                <div class="form-group">
                    <label>附件數量 (可能包含重覆計算)</label>
                    <input type="text" class="form-control" value="<?php echo escape($information['num_accessories']); ?>" readonly />
                </div>

            </div>
        </div>

    </div>
</div>

<?php
    //pr($information);
?>

